/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package futbol;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author osco
 */
public class jugadores extends javax.swing.JFrame {
    conexion_bd con = new conexion_bd();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    /**
     * Creates new form jugadores
     */
    public jugadores() {
        initComponents();
        setLocationRelativeTo(null);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        COMBO = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        APELLIDO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CATEGORIA = new javax.swing.JTextField();
        TURNO = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TJUGADORES = new javax.swing.JTable();
        FECHA = new com.toedter.calendar.JDateChooser();
        REGISTRO = new javax.swing.JButton();
        EDITAR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        COMBO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "ADMIN", "SECRETARIO" }));
        COMBO.setBorder(javax.swing.BorderFactory.createTitledBorder("TIPO USUARIO"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        NOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOMBREActionPerformed(evt);
            }
        });

        jLabel2.setText("NOMBRE");

        ID.setEnabled(false);
        ID.setRequestFocusEnabled(false);
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        jLabel3.setText("APELLIDO");

        jLabel4.setText("FECHA DE MACIMINETO");

        jLabel5.setText("CATEGORIA");

        jLabel6.setText("TURNO");

        CATEGORIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CATEGORIAActionPerformed(evt);
            }
        });

        TURNO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "MAÑANA", "TARDE" }));
        TURNO.setBorder(null);

        TJUGADORES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "APELLIDO", "FECHA", "CATEGORIA", "TURNO"
            }
        ));
        TJUGADORES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TJUGADORESMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TJUGADORES);

        FECHA.setDateFormatString("yyyy-MM-dd");

        REGISTRO.setText("REGISTRAR");
        REGISTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTROActionPerformed(evt);
            }
        });

        EDITAR.setText("EDITAR");
        EDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITARActionPerformed(evt);
            }
        });

        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (1).png"))); // NOI18N
        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(REGISTRO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EDITAR)
                                .addGap(18, 18, 18)
                                .addComponent(ELIMINAR))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel1))
                                    .addGap(54, 54, 54)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(NOMBRE)
                                            .addComponent(APELLIDO, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                                    .addGap(53, 53, 53)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CATEGORIA, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                        .addComponent(TURNO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FECHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(FECHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(TURNO, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(REGISTRO)
                    .addComponent(EDITAR)
                    .addComponent(ELIMINAR))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOMBREActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void CATEGORIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CATEGORIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CATEGORIAActionPerformed

    private void REGISTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTROActionPerformed
        // TODO add your handling code here:
        agregar();
        listar();
        nuevo();
    }//GEN-LAST:event_REGISTROActionPerformed

    private void TJUGADORESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TJUGADORESMouseClicked
        // TODO add your handling code here:
        int fila = TJUGADORES.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se Selecciono");
        }else{
            id = Integer.parseInt((String)TJUGADORES.getValueAt(fila,0).toString());
            String nom = (String) TJUGADORES.getValueAt(fila,1);
            String app = (String) TJUGADORES.getValueAt(fila,2);
            String turno = (String) TJUGADORES.getValueAt(fila,4);
            ID.setText(""+id);
            NOMBRE.setText(nom);
            APELLIDO.setText(app);
            TURNO.setToolTipText(turno);
        }
    }//GEN-LAST:event_TJUGADORESMouseClicked

    private void EDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITARActionPerformed
        // TODO add your handling code here:
        modificar();
        listar();
        nuevo();
    }//GEN-LAST:event_EDITARActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        // TODO add your handling code here:
        eliminar();
        listar();
        nuevo();
    }//GEN-LAST:event_ELIMINARActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        adminMenu abrir = new adminMenu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    void listar(){
        String sql=("select * from jugadores");
        try{
            cn = con.conectar();
            st = cn.createStatement();
            rs=st.executeQuery(sql);
            Object[]jugadores= new Object[6];
            modelo =(DefaultTableModel)TJUGADORES.getModel();
            while(rs.next()){
                jugadores[0]=rs.getInt("id_jugador");
                jugadores[1]=rs.getString("nombre");
                jugadores[2]=rs.getString("apellido");
                jugadores[3]=rs.getDate("nacimiento");
                jugadores[4]=rs.getString("categoria");
                jugadores[5]=rs.getString("turno");
                modelo.addRow(jugadores);
            }
            TJUGADORES.setModel(modelo);
        }catch(Exception e){
        
        }
    }
    void agregar(){
        String nombre=NOMBRE.getText();
        String app=APELLIDO.getText();
        String fecha =((JTextField)FECHA.getDateEditor().getUiComponent()).getText();
        String categoria=CATEGORIA.getText();
        String turno=TURNO.getSelectedItem().toString();
        if (nombre.equals("") || app.equals("")||fecha.equals("") || categoria.equals("") || turno.equals("")) {
            JOptionPane.showMessageDialog(null, "OBLIGATORIO INSERTAR DATOS!!!");
        }else{
            String sql="insert into jugadores(nombre,apellido,nacimiento,categoria,turno)values('"+nombre+"','"+app+"','"+fecha+"','"+categoria+"','"+turno+"')";
            try{
                cn=con.getConcection();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"JUGADOR REGISTRADO");
                limpiarTabla(modelo);
            }catch(Exception e){
            
            }
        }
        
        
    }
    void modificar(){
        String nombre=NOMBRE.getText();
        String app=APELLIDO.getText();
        String fecha =((JTextField)FECHA.getDateEditor().getUiComponent()).getText();
        String categoria=CATEGORIA.getText();
        String turno=TURNO.getSelectedItem().toString();
        String sql ="update jugadores set nombre='"+nombre+"',apellido='"+app+"',nacimiento='"+fecha+"',categoria='"+categoria+"',turno='"+turno+"' where id_jugador="+id;
        if (nombre.equals("") || app.equals("")||fecha.equals("") || categoria.equals("") || turno.equals("")) {
            JOptionPane.showMessageDialog(null,"Debe Ingresar datos");
        }else{
            try{
                cn = con.getConcection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "JUGADOR MODIFICADO");
                limpiarTabla(modelo);
            }catch(Exception e){
            
            }
        }
    }
    void eliminar(){
        int filaseleccionado = TJUGADORES.getSelectedRow();
        if (filaseleccionado==1) {
            JOptionPane.showMessageDialog(null,"Debe Seleccionar Fila");
        }else{
            String sql="delete from jugadores where id_jugador="+id;
                try{
                    cn=con.getConcection();
                    st=cn.createStatement();
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"JUGADOR ELIMINADO");
                    limpiarTabla(modelo);
                }catch(Exception e){
                
                }
        }
    }
    void nuevo(){
        NOMBRE.setText("");
        APELLIDO.setText("");
        FECHA.setDateFormatString("");
        CATEGORIA.setText("");
    }
    void limpiarTabla(DefaultTableModel modelo){
        for(int i=0; i<=TJUGADORES.getRowCount(); i++){
            modelo.removeRow(i);
            i=i-1;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jugadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField APELLIDO;
    private javax.swing.JTextField CATEGORIA;
    private javax.swing.JComboBox<String> COMBO;
    private javax.swing.JButton EDITAR;
    private javax.swing.JButton ELIMINAR;
    private com.toedter.calendar.JDateChooser FECHA;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JButton REGISTRO;
    private javax.swing.JTable TJUGADORES;
    private javax.swing.JComboBox<String> TURNO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
